FROM armv7/armhf-debian:latest
MAINTAINER <daniel.jam.finneran@hpe.com>

RUN apt-get update
RUN apt-get install -y make wget gcc libssl-dev libjson-c-dev

RUN wget -O bind.tar.gz https://www.isc.org/downloads/file/bind-9-10-4-p2/?version=tar-gz

RUN tar -xvzf bind.tar.gz

RUN cd /bind-9.10.4-P2
RUN ./configure --enable-fullreport


EXPOSE 53

CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]

