FROM armv7/armhf-debian:latest
MAINTAINER <daniel.jam.finneran@hpe.com>

RUN echo "deb http://ftp.de.debian.org/debian stretch main" >> /etc/apt/sources.list

RUN apt-get update

RUN apt-get upgrade -y

COPY bind9_9.10.3.dfsg.P4-10.1_armhf.deb /

RUN dpkg -i bind9_9.10.3.dfsg.P4-10.1_armhf.deb 

EXPOSE 53

CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]

